[32mINFO[0m:     [02-05-2024 19:23:00] Set chroma_server_nofile to 65535
[32mINFO[0m:     [02-05-2024 19:23:33] Set chroma_server_nofile to 65535
[32mINFO[0m:     [02-05-2024 19:23:33] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component System
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component SqliteDB
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component QuotaEnforcer
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component Posthog
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component LocalSegmentManager
[36mDEBUG[0m:    [02-05-2024 19:23:33] Starting component SegmentAPI
[32mINFO[0m:     [02-05-2024 19:23:33] Started server process [[36m14805[0m]
[32mINFO[0m:     [02-05-2024 19:23:33] Waiting for application startup.
[32mINFO[0m:     [02-05-2024 19:23:33] Application startup complete.
[32mINFO[0m:     [02-05-2024 19:23:33] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[31mERROR[0m:    [02-05-2024 20:37:29] Collection a812ee1d-7bf8-4719-bba8-0551dd91182b does not exist.
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 82, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 96, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/auth/fastapi.py", line 241, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 440, in get_collection
    return self._api.get_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/api/segment.py", line 261, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection a812ee1d-7bf8-4719-bba8-0551dd91182b does not exist.
[32mINFO[0m:     [02-05-2024 20:37:29] 127.0.0.1:50829 - "GET /api/v1/collections/a812ee1d-7bf8-4719-bba8-0551dd91182b HTTP/1.1" 500
[32mINFO[0m:     [02-05-2024 20:37:29] 127.0.0.1:50829 - "POST /api/v1/collections HTTP/1.1" 200
[36mDEBUG[0m:    [02-05-2024 20:37:33] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [02-05-2024 20:37:33] 127.0.0.1:50829 - "POST /api/v1/collections/b06842cc-ce9b-4900-90e1-a4b00f7de621/add HTTP/1.1" 201
[32mINFO[0m:     [02-05-2024 20:37:33] 127.0.0.1:50829 - "POST /api/v1/collections/b06842cc-ce9b-4900-90e1-a4b00f7de621/add HTTP/1.1" 201
[32mINFO[0m:     [02-05-2024 20:37:33] 127.0.0.1:50829 - "POST /api/v1/collections/b06842cc-ce9b-4900-90e1-a4b00f7de621/query HTTP/1.1" 200
